site_name: Conductor Documentation
theme: windmill
site_description: Concuctor cloud rendering on demand
repo_url: https://github.com/AtomicConductor/conductor_client
copyright: Conductor Technologies


site_url: https://www.conductortech.com
site_description: Project documentation with Markdown.
site_author: MkDocs Team


nav:
  - Home: index.md
  - Install client tools: install.md
  - Submitters:
    - Clarisse: submitters/clarisse.md
    - Maya: submitters/maya.md
    - Nuke: submitters/nuke.md
  - 'Web dashboard': 
    - Jobs: dashboard/jobs.md
  - Support: https://example.com/
  - Bug Tracker: https://example.com/
  - Meta: meta.md

extra_css:
  - css/autumn.css
  - css/codetabs.css
  - css/extra.css


markdown_extensions:
  - codehilite
  - admonition 
  - meta
  - markdown_fenced_code_tabs:
      template: 'default'
  - toc:
      permalink: true
 

copyright: Copyright &copy; 2019 , Conductor Technologies.
