site_name: Conductor Documentation
theme: windmill
site_description: Concuctor cloud rendering on demand
repo_url: https://github.com/AtomicConductor/conductor_client
copyright: Conductor Technologies


site_url: https://www.conductortech.com
site_description: Project documentation with Markdown.
site_author: MkDocs Team


nav:
  - Home: index.md
  - Install client tools: install.md
  - Submitters:
    - Clarisse: submitters/clarisse.md
    - Maya: submitters/maya.md
    - Nuke: submitters/nuke.md
  - 'Web dashboard': 
    - Jobs: dashboard/jobs.md
  - Support: https://example.com/
  - Bug Tracker: https://example.com/

extra_css:
  - css/autumn.css

markdown_extensions:
  - codehilite
  - admonition 
  - meta

# copyright: Copyright &copy; 2019 , Maintained by the <a href="/about/release-notes/#maintenance-team">Conductor Team</a>.
# # google_analytics: ['UA-27795084-5', 'mkdocs.org']

